### ISSUE TITLE
create a todo list project using html css and js

### ISSUE THREAD

**Issue by acash1809** [acash1809/Open-Source#1]
create above mentioned project and add it to folder /Projects/{project-name}/

To get your PR accepted please star and fork this repo then upload your project

**Comment by prachinegi17** [comment]
Please assign this task to me.

**Comment by acash1809** [comment]
@prachinegi17 assigned now you can start working

**Comment by DeputyBerry** [comment]
assign me please! 😃

**Comment by acash1809** [comment]
@DeputyBerry this issue is already assigned to someone else but you can create a new issue ill label it as hacktoberfest
But do not post any dsa or calculator project
