### ISSUE TITLE
Create a hotel review website using html css and js

### ISSUE THREAD

**Issue by acash1809** [acash1809/Open-Source#10]
create a website for hotel review using html, CSS and JS 
then add it to path-
``` Projects/{your project name}/```

To get your PR accepted Star this Repository and fork it
then add your project and create a PR.

**Comment by avezqureshi14** [comment]
Hey bro is this, the same project you goona assign me ?

**Comment by acash1809** [comment]
yup @avezqureshi14 you wanna work on it?
ok assigning it to you

**Comment by avezqureshi14** [comment]
Thanks bro @acash1809
