### ISSUE TITLE
Add a machine learning model

### ISSUE THREAD

**Issue by acash1809** [acash1809/Open-Source#13]
Add a Machine learning model. Try to comment your code as much as possible to make it easy to understand for those who are new to machine learning.

To get your PR accepted-
- Star this repository( which is not necessary but it will encourage me )then fork it.
- Add your code to path ```/Machine_Learning_Model/{your project name}/```
- Create a Pull Request

If you follow above steps properly only then your PR will be accepted.

**Comment by bhoomi1310** [comment]
Please assign me this issue

**Comment by acash1809** [comment]
@bhoomi1310 assigned.
