### ISSUE TITLE
Create an airline reservation system

### ISSUE THREAD

**Issue by acash1809** [acash1809/Open-Source#15]
Create an airline reservation system 

To get your PR accepted-

Star this repository( which is not necessary but it will encourage me )then fork it.
Add your code to path ```/Projects/{your project name}/```
Create a Pull Request
If you follow above steps properly only then your PR will be accepted.

**Comment by Akash494** [comment]
Hello @acash1809.  This is Akash Gola. I have seen your issue and i think i can help you with this one. Please assign me the issue topic. 
Thank you

**Comment by acash1809** [comment]
@Akash494 assigned Now you can start working on it.
