### ISSUE TITLE
create a Spotify clone

### ISSUE THREAD

**Issue by acash1809** [acash1809/Open-Source#16]
Create a Spotify clone 

To get your PR accepted-

Star this repository( which is not necessary but it will encourage me) then fork it.
Add your code to path ```/Projects/{your project name}/```
Create a Pull Request
If you follow above steps properly only then your PR will be accepted.

**Comment by Akash494** [comment]
Please assign me this issue.

**Comment by acash1809** [comment]
@Akash494 assigned bro now you can start working
