### ISSUE TITLE
Create a simple About_Us page

### ISSUE THREAD

**Issue by acash1809** [acash1809/Open-Source#26]
Create a simple about_us page and add name of contributors contributed to this repo and this repository link to it.

Steps:-

- Create a folder About_Us and add your project in it.
- you can use any technology you prefer.
- To get your Pr accepted please Star this repo and fork it
- upload then create PR.

Goodluck for your work :) happy hacktober

**Comment by shivam-Purohit** [comment]
Hey @acash1809  Can you provide the structure of the page , I can work on this if you like.

**Comment by acash1809** [comment]
@shivam-Purohit 
![image](https://user-images.githubusercontent.com/68990244/198585660-29e3e846-c9a8-4907-98c9-a72db57c941b.png)

it does not need to be exact similar you can make changes accordingly and take it easy.
Assigning you.

**Comment by acash1809** [comment]
Now you can start working on it.

**Comment by shivam-Purohit** [comment]
Thankyou @acash1809 
Where should I get the icons/logo or use it my own ?

**Comment by acash1809** [comment]
@shivam-Purohit you can use your own logo, the above image I used is only for reference

**Comment by shivam-Purohit** [comment]
![Screenshot (92)](https://user-images.githubusercontent.com/91889807/198659004-489e6917-b99f-439f-b2f4-bdb29be232dc.png)
Have a look at this @acash1809 .
One doubt I have is should I manually enter the contributors name in this repo or keep it like this only. And also couldn`t get the upload your project thing.
Suggest some changes if required.

**Comment by acash1809** [comment]
@shivam-Purohit can you change name "club gamma" to "open source" and everything else is good.
good job.

**Comment by shivam-Purohit** [comment]
yes sure , after changes should I open a PR?

**Comment by acash1809** [comment]
sure @shivam-Purohit , you can
