### ISSUE TITLE
Create a food blog website using html, CSS and JS

### ISSUE THREAD

**Issue by acash1809** [acash1809/Open-Source#3]
Create a  food blog website if you can add comments box then please consider doing so.

To get your PR accepted please Star this repository and fork it.
Upload the required projects and create a pr.

If you do above steps properly we will accept your PR.

**Comment by acash1809** [comment]
Please upload your folder in /Projects/{your project name}/

**Comment by anishrocco** [comment]
i wanna make this project. please assign me

**Comment by acash1809** [comment]
@anishrocco assigned now you can start working on it.

**Comment by anishrocco** [comment]
With pleasure

**Comment by avezqureshi14** [comment]
@acash1809 bro i did also like to work on this project, You can check out my work here https://avezqureshi.netlify.app/

**Comment by acash1809** [comment]
@avezqureshi14 would you like to work on a hotel review blog?
if so ill create new issue for you

**Comment by anishrocco** [comment]
Then i have to try it .... 1st let me check it

**Comment by acash1809** [comment]
@anishrocco @avezqureshi14  ok you both can work on this food blog website

**Comment by avezqureshi14** [comment]
Thanks @acash1809 for assigning me this one

**Comment by avezqureshi14** [comment]
> @avezqureshi14 would you like to work on a hotel review blog? if so ill create new issue for you

Yeah @acash1809 I will be happy to work on it, but I did like to know is the work regarding Front End or Full Stack

**Comment by anishrocco** [comment]
I'm gonna submit it by today.... Actually there was some issues of
network.... But tdy i will manage it

**Comment by acash1809** [comment]
@anishrocco okay no worries.

**Comment by acash1809** [comment]
@avezqureshi14 you just need to work on font end
(but if you've already created a full stack web then you can also submit that)
i saw your website its good, excellent work there!

**Comment by avezqureshi14** [comment]
bro @acash1809 i had created the pull request please review and merge it 
Demo Video of the work
[hacktober2.zip](https://github.com/acash1809/Open-Source/files/9870357/hacktober2.zip)

**Comment by acash1809** [comment]
@avezqureshi14 nice work!

**Comment by acash1809** [comment]
@anishrocco don't worry about it ill also accept yours as well as this repo is created for everyone.
