### ISSUE TITLE
Create a program for Data Visualisation using matplotlib

### ISSUE THREAD

**Issue by acash1809** [acash1809/Open-Source#32]
Upload a your project in folder-
```DataVisualisation/{project name}/```

To get your PR accepted please Star this repository and Fork it
Add your project in directed path and create PR.

**Comment by gitranjit** [comment]
Hey can you I work on this? please let me know if I can, and a little more information about project.

**Comment by acash1809** [comment]
@gitranjit this issue was created during hacktoberfest 2022 now we are closing this issue.
