### ISSUE TITLE
Create a student management system.

### ISSUE THREAD

**Issue by acash1809** [acash1809/Open-Source#35]
Upload your project in Projects folder.

**Comment by siddhesh-coder** [comment]
plz assign me this issue

**Comment by Akash494** [comment]
Please assign me the issue.

**Comment by acash1809** [comment]
@siddhesh-coder assigned dont forget to star this repo

**Comment by siddhesh-coder** [comment]
yes.

**Comment by siddhesh-coder** [comment]
hi you want it in a interface manner or just can run in terminal.

**Comment by acash1809** [comment]
@siddhesh-coder whatever you prefer

**Comment by siddhesh-coder** [comment]
ok I will go with the terminal one for interface it will require too much time.

**Comment by acash1809** [comment]
ok
