### ISSUE TITLE
Create an Instagram clone project

### ISSUE THREAD

**Issue by acash1809** [acash1809/Open-Source#4]
Create an Instagram clone project.
add your project in path /Projects/{your project name}/

To get your Pr accepted please Star this repo and fork it.
Add your project and create a pr.

**Comment by prachinegi17** [comment]
please accept my request to work on the issue.

**Comment by anushreevarshney** [comment]
hello, I want to work on this issue

**Comment by acash1809** [comment]
@anushreevarshney assigned
